name: gee
channels:
    - conda-forge
dependencies:
    - cartopy
    - datapane
    - gdal
    - geopandas
    - imageio
    - ipyleaflet
    - jupyterlab=3
    - keplergl
    - localtileserver
    - nodejs
    - osmnx
    - palettable
    - pip
    - plotly
    - psycopg2
    - pydeck
    - pydeck-earthengine-layers
    - scipy
    - sqlalchemy
    - tifffile
    - xarray_leaflet
    - pip:
          - git+git://github.com/giswqs/leafmap
          - git+git://github.com/giswqs/geemap
