name: gee
channels:
    - conda-forge
dependencies:
    - cartopy
    - datapane
    - geemap
    - geopandas
    - imageio
    - ipyleaflet
    - jupyterlab=3
    - keplergl
    - leafmap
    - nodejs
    - osmnx
    - psycopg2
    - pydeck
    - scipy
    - sqlalchemy
    - tifffile
    - xarray_leaflet
