name: gee
channels:
    - conda-forge
dependencies:
    - cartopy
    - datapane
    - gdal
    - geemap
    - geopandas
    - imageio
    - ipyleaflet
    - jupyterlab=3
    - keplergl
    - leafmap
    - localtileserver
    - nodejs
    - osmnx
    - palettable
    - psycopg2
    - pydeck
    - pydeck-earthengine-layers
    - scipy
    - sqlalchemy
    - tifffile
    - xarray_leaflet
