site_name: geemap

theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Installation: installation.md
  - Get Started: get-started.md
  - Usage: usage.md
  - Tutorials: tutorials.md
  - FAQ: faq.md
  - API Reference:
      - geemap module: geemap.md
      - basemaps module: basemaps.md
      - conversion module: conversion.md
      - eefolium module: eefolium.md
      - legends module: legends.md
      - utilities module: utils.md